---
kind: pipeline
name: node-v10
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: node:10
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional
    -   name: tests
        image: node:10
        commands:
            - npm run test

trigger:
    branch:
        - master
    event:
        exclude:
            - cron

---
kind: pipeline
name: node-v12
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: node:12
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional
    -   name: tests
        image: node:12
        commands:
            - npm run test

trigger:
    branch:
        - master
    event:
        exclude:
            - cron

---
kind: pipeline
name: deps
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: node:12
        commands:
            - node -v
            - npm -v
            - npm i --no-save --quiet --no-optional
        depends_on: [ clone ]
    -   name: audit
        image: node:12
        commands:
            - npm audit
        depends_on: [ clone ]
    -   name: outdated
        image: node:12
        commands:
            - npm run check-outdated
        depends_on: [ install ]

trigger:
    branch:
        - master
---
kind: signature
hmac: 954738fdd9cecf7fdaa6b6f10c0f4c33b869dfb1176cb7fb2f8f5fc923ff1fb8

...
