kind: pipeline
name: compliance
type: docker

steps:
    -   name: linter
        image: node:12-alpine
        commands:
            - apk add git tar
            - npm i --quiet --no-save --no-optional --no-audit
            - npm run lint

---
kind: pipeline
name: tests
type: docker

steps:
    -   name: tests
        image: node:12-alpine
        commands:
            - apk add git tar
            - npm i --quiet --no-save --no-optional --no-audit
            - npm run test
