strictPeerDependencies: true
strictDepBuilds: true
onlyBuiltDependencies:
  - bufferutil
  - classic-level
  - esbuild
  - node-datachannel
  - utf-8-validate
  - utp-native
ignoredBuiltDependencies:
  - core-js
